source 'http://rubygems.org'

gem 'rake'
gem 'sinatra'
#gem 'sinatra-contrib'
gem 'sinatra-activerecord'
#gem 'rack-contrib', :git => 'git://github.com/rack/rack-contrib.git'
gem 'activerecord', require: 'active_record'
gem 'pg'
#gem 'yajl-ruby', :require => 'yajl'
#gem 'dalli'
#gem 'unicorn', '~> 4.1.1'
gem 'haml'
#gem 'compass', '~> 0.12.alpha.0'
gem 'sass'
#gem 'sprockets'
#gem 'sprockets-helpers', '~> 0.2'
#gem 'sprockets-sass'
gem 'coffee-script'

group :development, :test do
  #gem 'rspec', '~> 2.7.0.rc1'
  #gem 'rack-test'
  #gem 'simplecov'
  #gem 'capistrano', '=2.8.0'
  #gem 'capistrano-ext', '=1.2.1'
  # gem 'vcr'
  # gem 'webmock'
  # gem 'timecop'
end
