---
common: &common
  adapter: postgresql
  host: localhost
  pool: 5
  username: robert

development:
  database: jeans_shop_development
  password: '1'
  <<: *common

#test:
#  database: strider_test
#  password: lysning
#  min_messages: WARNING
#  <<: *common

#staging:
#  database: strider_staging
#  password: lysning
#  <<: *common

#production:
#  <<: *common
#  host: appsdb.o5.no
#  database: strider_production
#  password: lysning
